### ISSUE TITLE
[Bug] Disconnted with VTS when hotkey selected

### ISSUE THREAD

**Issue by dubistowch** [Cazzar/VTSDeck-Plugin#27]
Version: 1.0.0
AX310 (Windows)
Software: 1.1.2.18
Firmware: 1.5.10.37
Driver 1.0.64.30

Connection was estiablished at once, disconnected when configured hotkeys
* Have been restarted the VTS API server
* Have been restarted Creator Central

![image](https://user-images.githubusercontent.com/81440008/198507437-56a72533-fe6c-4b2c-8f25-9c1060fe7686.png)

**Comment by Cazzar** [comment]
Hey @dubistowch 

AVerMedia have contacted me in regards to this sometimes happening, there has also been some discussions about some others seeing this kind of thing happening for other applications, so we are trying to work out as part on the VTubeStudio discord.

If you are able to, are you able to provide the log file from `%appdata%\AVerMedia Creator Central\packages\dev.cazzar.vtubestudio\plugin-log.log`?

**Comment by Cazzar** [comment]
From some work with AVerMedia it has been identified that there was an error in my handling code for CreatorCentral, this has now been fixed in new releases.
