### ISSUE TITLE
VTS Authentication 

### ISSUE THREAD

**Issue by Ben-Lillie** [Cazzar/VTSDeck-Plugin#62]
Been a while since I have done any C# but I can't see a method for authenticating I can run the project find I just get the following JSON

{"apiName":"VTubeStudioPublicAPI","apiVersion":"1.0","timestamp":1672773023911,"messageType":"APIError","requestID":"3ae797952aa2453488f79703e40435c9","data":{"errorID":8,"message":"Current session is not authenticated. The only requests you can send without authenticating are: [APIStateRequest, AuthenticationTokenRequest, AuthenticationRequest]"}

I must be missing something obvious. If you need more info I am happy to provide.

**Comment by Cazzar** [comment]
Are you trying to run the project as-is, or with some modifications?

The way the VTubeStudio authentication is designed, is it should authenticate on connection based off the persisted VTS token:

https://github.com/Cazzar/VTSDeck-Plugin/blob/d5096349e5950b7665bcc1e26f451ca85004157f/VTubeStudioAPI/VTubeStudioImpl.cs#L98-L105

**Comment by Ben-Lillie** [comment]
Cloned, opened with Visual Studio 2022 and ran. I've ran it and it's not actually executing that snippet. I can't see `VTubeStudioImpl` being setup in the VTubeStudio AX310 project `Program.cs` either.

**Comment by Cazzar** [comment]
Ah, that gets set up via the Hosted application Container, simply running the application means it won't actually fully set up.

As this is designed as a plugin for CreatorCentral it actually is intended to get executed by CreatorCentral directly which starts it with specific parameters here: https://github.com/AVerMedia-Technologies-Inc/CreatorCentralSDK/wiki/Registration-Flow#compiled-package-registration

**Comment by Ben-Lillie** [comment]
Ah thank you, is it possible to extract the VTubeStudio API and use it as a standalone away from CreatorCentral or is it to ingrained. Just looking to do a few bits with VTS using C# and you seem to have the best C~ implementation. No worries if not just having some fun. 😊

**Comment by Cazzar** [comment]
It would be possible, though as I don't have ait documented, if you create your own version of the `AuthManager` and `VTubeStudioPluginInformation` and then strip the `ConfigureServices()` call to just registering your own hosted service, and the `ConfigureVTubeStudio()` call to run your plugin code it should work.

If you need a hand, I am also on the VTubeStudio discord, so feel free to reach out there as well, right now a lot of the events and code is tailored specifically to the needs of the streamdeck and AX310 plugins though it should be easy enough to add more if needed.

**Comment by Ben-Lillie** [comment]
Nice, I'll take a look at it and see if I can get it going thanks for the help. I'm in the VTube Studio discord as well so will drop a message in there if I need a hand.
